// angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { NgForm } from '@angular/forms';

import { environment } from '../../environments/environment';

class Token {
	token: string ="";
}

class Credential{
	email:string = "";
	password:string = "";
}

type State = "Empty" | "Filled" | "Loading" | "Error";

@Component({
	selector: 'app-login',
	templateUrl: './login.component.html',
	styleUrls: ['./login.component.css']
})
export class LoginComponent {

	credential:Credential = new Credential();
	state:State = "Empty";

	constructor(
		private httpClient: HttpClient,
		private router: Router
	){}

    onInputChanged(){
    	this.state = (this.credential.email.length * this.credential.password.length) == 0 ? "Empty" : "Filled";
    }

    submit(){
    	this.state = "Loading";
    	this.httpClient.post<Token>(environment.url+"/login",this.credential).subscribe(
			r => {
			 localStorage.setItem('token', r.token);
			 this.router.navigate(['/discussions']);
			},
			err => {
				this.state = "Error";
			}
    	);
    }

}

<h1 class="ml-4">Identification</h1>
<hr />
<form>
	<div class="login-form mx-4">
		<label htmlFor="email">Email address</label>
		<input type="email" class="form-control" id="email" name="email" required />
	</div>
	<div class="form-group mt-2 mx-4">
		<label htmlFor="password">Password</label>
		<input type="password" autocomplete="current-password" class="form-control" id="password" name="password" required />
	</div>
	<input type='submit' value="Submit" class="btn btn-secondary ml-4"/>
</form>

// react/my-app-react/src/login.js
import React from 'react';
import ReactDOM from 'react-dom';
import 'bootstrap/dist/css/bootstrap.min.css';

class Login extends React.Component {
	constructor(props) {
    	super(props);
    	this.state = {mail: '', password: ''};
  	}

	changeMail = (event) => {
    	this.setState({mail: event.target.value});
    	localStorage.setItem('mail', event.target.value);
  	}

  	changePassword = (event) => {
  		this.setState({password: event.target.value});
  		localStorage.setItem('password', event.target.value);
  	}

  	formSubmited = (event) => {
    	event.preventDefault();
    	this.props.history.push('/ListDiscussions');
  	}

	render() {
		return (
			<div>
				<h1 className="ml-4">Identification</h1>
				<hr />
				<form onSubmit={this.formSubmited.bind(this)}>
				  <div className="login-form mx-4">
				    <label htmlFor="email">Email address</label>
				    <input type="email" className="form-control" id="email" name="email" onChange={this.changeMail}required />
				  </div>
				  <div className="form-group mt-2 mx-4">
				    <label htmlFor="password">Password</label>
				    <input type="password" autocomplete="current-password" className="form-control" id="password" name="password" onChange={this.changePassword} required />
				  </div>
				  <input type='submit' value="Submit" className="btn btn-secondary ml-4"/>
				</form>
			</div>
		);
	}
}

export default Login;

ReactDOM.render(
	<Login />,
	document.getElementById('root')
);
