// angular/src/app/discussion/show/show.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, ParamMap, Params } from '@angular/router';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import jwt_decode from 'jwt-decode';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { environment } from '../../../environments/environment';

class ApiMessage {
	id:number;
	user:string;
	content:string;
	date:Date;
}

class Message {
	id:number;
	user:string;
	content:string;
	date:string;
	constructor(am:ApiMessage) {
		this.user = am.user;
		this.content = am.content;
		this.date = moment(am.date).locale("fr").format("LLL");
		this.id = am.id;
	}
}

class Credential{
	content:string = "";
}

@Component({
	selector: 'app-show',
	templateUrl: './show.component.html',
	styleUrls: ['./show.component.css']
})

export class ShowComponent implements OnInit {
	discussion:Array<Message>=[];
	id:number = Number(localStorage.getItem("discussionId"));
	credential:Credential = new Credential();
	subject:string = localStorage.getItem("subject");
	actualUserMail:string = jwt_decode(localStorage.getItem('token')).mail;

	constructor(
		private httpClient: HttpClient,
    	private route: ActivatedRoute,
    	private router: Router,
    	private activatedRoute: ActivatedRoute
    ) {};

	ngOnInit(): void {
		let headers = {
	    	'Authorization': 'Bearer ' + localStorage.getItem('token')
		};
		this.httpClient.get<Array<ApiMessage>>(environment.url + "/discussions/" + this.id + "/messages", { headers: headers })
		.subscribe(
			(r:Array<ApiMessage>) => {
				this.discussion = r.map(e=>new Message(e)); 
			}
		);
	}

	newMessage(){
		let headers = {
	    	'Authorization': 'Bearer ' + localStorage.getItem('token')
		};
		let body = { 
			"content": this.credential.content
		};
    	this.httpClient.post<Message>(environment.url+"/discussions/" + this.id + "/messages", body, { headers: headers }).subscribe(
			// r => { 
			// 	this.discussion.push({ id: r.id, user: this.actualUserMail, content: r.content, date: r.date});
			// }
			d => {
        		let newState:Array<Message> = []; 
        		this.discussion.forEach(d=>newState.push(d));
        		newState.push({date: d.date, user:this.actualUserMail, content:d.content,id:d.id});
        		this.discussion = newState;  
    		}
    	);
    }

    deleteMessage(id){
		let headers = {
	    	'Authorization': 'Bearer ' + localStorage.getItem('token')
		};
    	this.httpClient.delete(environment.url+"/discussions/messages/" + id, { headers: headers }).subscribe(
			r => {
				this.discussion = this.discussion.filter(item => item.id != id);
			}
    	);
    }

}

<h1 class="mt-4 ml-4">Discussion about {{this.subject}}</h1>
<hr />
<form>
	<div class="form-group mx-4">
		<label>Add a message</label>
		<textarea class="form-control" name="content" rows="1" [(ngModel)]="credential.content" required></textarea>
	</div>
	<button class="btn btn-primary ml-4 mb-4" (click)="newMessage()">
		<span class="fa fa-plus mr-2"></span>
		Add a message
	</button>
</form>
<table class="table mx-4">
	<thead class="thead-light">
		<tr>
			<th scope="col">User
				<span class="fa fa-user ml-2"></span>
			</th>
			<th scope="col">Content
				<span class="fa fa-book-open ml-2"></span>
			</th>
			<th scope="col">Date
				<span class="fa fa-calendar-day ml-2"></span>
			</th>
			<th scope="col">Action</th>
		</tr>
	</thead>
	<tbody>
		<tr *ngFor="let item of discussion">
			<td>{{item.user.mail}}</td>
			<td>{{item.content}}</td>
			<td>{{item.date}}</td>
			<td>
				<button class="btn btn-sm btn-danger ml-2" (click)="deleteMessage(item.id)">
					<span class="fa fa-trash-alt justify-content-md-center"></span>
				</button>
			</td>
		</tr> 
	</tbody>
</table>

// react/my-app-react/src/show.js
import React from 'react';
import ReactDOM from 'react-dom';
import 'bootstrap/dist/css/bootstrap.min.css';
import { faSignOutAlt, faUser, faComments, faPlus, faEye, faTrashAlt, faBookOpen, faCalendarDay } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from '@fortawesome/fontawesome-svg-core';

class Show extends React.Component {
	_isMounted = false;
	constructor(props) {
    	super(props);
    	this.state = {
    		id: localStorage.getItem('id'),
    		content: '',
    		listItems: [],
    		subject : localStorage.getItem('subject')
    	};
   	}

   	componentDidMount() {
   		this._isMounted = true;
    	this.getData()
  	}

  	componentWillUnmount() {
    	this._isMounted = false;
  	}

  	getData() {
  		const email = localStorage.getItem("mail")
  		const password = localStorage.getItem("password")
  		let myInit = { method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Authorization' :'Basic '+btoa(email+":"+password)
            }
        };
        let myRequest = new Request('http://localhost:8080/discussions/' + this.state.id + "/messages", myInit);

        fetch(myRequest,myInit).then(r=>r.json()).then(data => {
  			let newState ={ listItems: [] }; 
  			data.forEach(d=>newState.listItems.push({date: d.date, user:d.user.mail, content:d.content,id:d.id}))
  			 if (this._isMounted) {
  				this.setState(newState);
  			}
  		}).catch(function(error) {
  			console.log('Problem with fetch operation: ' + error.message);
		});
  	}

  	setContent = (event) => {
    	this.setState({content: event.target.value});
  	}

  	signOut() {
		localStorage.clear()
		this.props.history.push('/');
  	}

	addMessage() {
  		const email = localStorage.getItem("mail")
  		const password = localStorage.getItem("password")
		fetch('http://localhost:8080/discussions/' + this.state.id +'/messages', {
  			method: 'POST',
  			headers: {
    			'Accept': 'application/json',
    			'Content-Type': 'application/json',
    			'Authorization' :'Basic '+btoa(email+":"+password)
  			},
  			body: JSON.stringify({
   	 			content: this.state.content,
  			})
		})
		.catch(function(error) {
  			console.log('Problem with fetch operation: ' + error.message);
		});
  	}

  	deleteItem(id){
  		const email = localStorage.getItem("mail")
  		const password = localStorage.getItem("password")
  		let myInit = { method: 'DELETE',
            headers: {
                'Content-Type': 'application/json',
                'Authorization' :'Basic '+btoa(email+":"+password)
            }
        };
        let myRequest = new Request('http://localhost:8080/discussions/messages/' + id, myInit);

        fetch(myRequest,myInit).then(data => {
  			let newState ={ listItems: this.state.listItems.filter(i=>i.id!==id) }; 
  			this.setState(newState);
  		}).catch(function(error) {
  			console.log('Problem with fetch operation: ' + error.message);
		});
  	}

	render() {
		const { listItems } = this.state
		return (
			<div>
				<nav className="navbar navbar-expand-lg navbar-light bg-light">
  					<span className="navbar-brand w-25">Forum de Jade</span>
			  		<button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    		<span className="navbar-toggler-icon"></span>
			  		</button>
			  		<div className="collapse navbar-collapse" id="navbarNav">
			    		<ul className="navbar-nav  w-50">
			    			<li className="nav-item active">
			        			<a className="nav-link mr-4" href="/List">List of discussions 
			        				<span className="sr-only"></span>
			        			</a>
			      			</li>
			      			<li className="nav-item active">
			        			<a className="nav-link ml-4" href="/New">New discussion 
			        				<span className="sr-only"></span>
			        			</a>
			      			</li>
			    		</ul>
    					<span className="navbar-text ml-4" id="user">
    						<FontAwesomeIcon icon={faUser} className="mx-2" />
    						: {localStorage.getItem('mail')}
    					</span>
    					<span className="ml-4">
    						<button onClick={this.signOut.bind(this)} className="btn btn-sm btn-secondary ml-4">
								<FontAwesomeIcon icon={faSignOutAlt} />
   							</button>
   						</span>
		  			</div>
				</nav>
				<h1 className="mt-4 ml-4">Discussion about: {this.state.subject}</h1>
				<hr />
				<form>
					<div className="form-group mx-4">
	    				<label>Add a message</label>
	    				<textarea className="form-control" name="content" rows="1" onChange={this.setContent} required></textarea>
	  				</div>
	  				<button type="submit" className="btn btn-primary ml-4 mb-4" onClick={() => this.addMessage()}>
	  					<FontAwesomeIcon icon={faPlus} className="mr-2"/>
	  					Add a message
	  				</button>
	  			</form>
				<table className="table mx-4">
  					<thead className="thead-light">
    					<tr>
      						<th scope="col">User
      							<FontAwesomeIcon icon={faUser} className="ml-2"/>
      						</th>
      						<th scope="col">Content
      							<FontAwesomeIcon icon={faBookOpen} className="ml-2"/>
      						</th>
      						<th scope="col">Date
      							<FontAwesomeIcon icon={faCalendarDay} className="ml-2"/>
      						</th>
      						<th scope="col">Action</th>
    					</tr>
  					</thead>
  					<tbody>
  						{
							listItems.map((item,index) => (
								<tr key={index}>
									<td>{item.user}</td>
									<td>{item.content}</td>
									<td>on {item.date.substring(0, 10)} at {item.date.substring(11, 16)}</td>
									<td>
										<button className="btn btn-sm btn-danger ml-2" onClick={()=>this.deleteItem(item.id)}>
											<FontAwesomeIcon icon={faTrashAlt} className="justify-content-md-center" />
										</button>
									</td>
								</tr> 
							))
						}
	  				</tbody>
	  			</table>
			</div>
		);
	}
}

export default Show;

ReactDOM.render(
	<Show />,
	document.getElementById('root')
);

library.add(faSignOutAlt, faUser, faComments, faPlus, faEye, faTrashAlt, faBookOpen, faCalendarDay);
